---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: minecrafts.controllers.illallangi.enterprises
spec:
  group: controllers.illallangi.enterprises
  names:
    kind: Minecraft
    plural: minecrafts
    shortNames:
    - minecraft
    - mc
    singular: minecraft
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Age of the instance
      jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - description: The Title of the instance
      jsonPath: .spec.title
      name: Title
      type: string
    - description: The Host Name of the instance
      jsonPath: .spec.hostName
      name: HostName
      type: string
    - description: The Domain Name to host the instance under
      jsonPath: .spec.domainName
      name: DomainName
      type: string
    - description: The URI Path to host the instance under
      jsonPath: .spec.uriPath
      name: URIPath
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          spec:
            properties:
              cert:
                properties:
                  issuerKind:
                    pattern: ^(((Cluster)?Issuer)|)$
                    type: string
                  issuerName:
                    type: string
                  organization:
                    type: string
                required:
                - issuerKind
                - issuerName
                - organization
                type: object
              data:
                properties:
                  claimName:
                    type: string
                  subPath:
                    default: ''
                    type: string
                required:
                - claimName
                type: object
              domainName:
                type: string
              gid:
                default: 1000
                type: integer
              hostName:
                type: string
              persistence:
                properties:
                  storage:
                    default: 128Gi
                    type: string
                  storageClassName:
                    type: string
                required:
                - storageClassName
                type: object
              plugins:
                default:
                - url: https://github.com/Masstrix/Eternal-Light/releases/download/1.7/EternalLight-1.7.jar
                - url: https://github.com/sladkoff/minecraft-prometheus-exporter/releases/download/v2.2.0/minecraft-prometheus-exporter-2.2.0.jar
                - url: https://dynmap.us/releases/Dynmap-3.2-beta-1-spigot.jar
                - url: https://media.forgecdn.net/files/912/629/dynmap-mobs-1.3.jar
                items:
                  type: object
                  properties:
                    url:
                      type: string
                  required:
                  - url
                type: array
              title:
                type: string
              uid:
                default: 1000
                type: integer
              uriPath:
                type: string
            required:
            - cert
            - data
            - domainName
            - hostName
            - persistence
            - title
            - uriPath
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/component: data
    app.kubernetes.io/name: minecraft
  name: minecraft-data
  namespace: fiftyeight-payload
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: x2-file

---
apiVersion: controllers.illallangi.enterprises/v1
kind: Minecraft
metadata:
  name: prosport
  namespace: fiftyeight-payload
spec:
  cert:
    issuerKind: ClusterIssuer
    issuerName: letsencrypt-production
    organization: FiftyEight Industries
  data:
    claimName: minecraft-data
    subPath: prosport
  domainName: fiftyeight.us
  hostName: prosport
  gid: 1061
  persistence:
    storageClassName: x2-block
  title: ProsPort
  uid: 1061
  uriPath: prosport

---
apiVersion: controllers.illallangi.enterprises/v1
kind: Minecraft
metadata:
  name: vanilla
  namespace: fiftyeight-payload
spec:
  cert:
    issuerKind: ClusterIssuer
    issuerName: letsencrypt-production
    organization: FiftyEight Industries
  data:
    claimName: minecraft-data
    subPath: vanilla
  domainName: fiftyeight.us
  hostName: vanilla
  gid: 1061
  persistence:
    storageClassName: x2-block
  title: Vanilla
  uid: 1061
  uriPath: vanilla